### ISSUE TITLE
Can not find the keys file

### ISSUE THREAD

**Issue by syuukawa** [simplesecure/hello-simpleid#1]
Can not find the keys file

**Comment by jehunter5811** [comment]
If you are trying to run this yourself locally, you'll need to create that file. The structure of the file is like this: 

`export function simpleIDKeys() {
  return {
    apiKey: "", 
    devId: ""
  }
}`

And the file should be placed at the root of the project. Of course you can obfuscate your keys anyway you'd like in your own projects :)

**Comment by syuukawa** [comment]
Got it ; Thanks

**Comment by syuukawa** [comment]
there is no problem; I have known how to do with it ;By the way I have translate the English to the Chinese : You can see it here ;https://www.jianshu.com/c/66310544fd58

**Comment by jehunter5811** [comment]
This is incredible!!! Do you mind if we share this with others? And do you have a twitter account we can mention when we do?

**Comment by syuukawa** [comment]
Yes, You can share this; 【https://twitter.com/locustszhou 】this is my twitter account .
