### ISSUE TITLE
About simpleIDKeys

### ISSUE THREAD

**Issue by syuukawa** [simplesecure/hello-simpleid#2]
1 - Now :
the simpleIDKeys is used by 【export function simpleIDKeys() { return { apiKey: "-Lms742ZqWeayC8U0qBP", devId: "jianshu" } }】
or  get from the config file just as keys;
But it is not user friendly；
When the DApp  is deployed, It can not be change;So there is just one user  can use the DApp;
 
2 - How can it get from the simpleIDKeys from SimpleID API;
So that anyone can use the DApp by SimpleID;

**Comment by jehunter5811** [comment]
Did you figure this out @syuukawa? I’d be happy to explain it if you still have questions.
